#hello
#hello
trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      mymachine
    steps:
    - script: docker build -t shahenvaz7/nodeapp:'$(Build.BuildId)' .

- stage: Uploading_artifacts
  displayName: Upload artifacts
  jobs:
  - job: uploading_artifacts
    displayName: uploading artifacts
    pool:
      mymachine
    steps:
    - script: npm version 1.0.$(Build.BuildId)
    - script: npm publish
    
    
- stage: Pushing_to_docker 
  displayName: Pushing to docker hub registry
  jobs:
  - job: Pushing
    displayName: Pushing
    pool:
      mymachine
    steps:
    - script: docker push shahenvaz7/nodeapp:'$(Build.BuildId)'
    
- stage: Deployment
  displayName: Deployment to k8s
  jobs:
  - job: Deployment
    displayName: Deployment
    pool:
      mymachine
    steps:
    - script: kubectl apply -f k8s/nodeApp.yml
    - script: kubectl apply -f k8s/nodeService.yml
    - script: kubectl apply -f k8s/mongodb.yml
    - script: kubectl apply -f k8s/mongodbservice.yml
    - script: kubectl set image deployment/nodeapp nodeapp=shahenvaz7/nodeapp:'$(Build.BuildId)'